### ISSUE TITLE
Improve Login Page Design and Functionality V2

### ISSUE THREAD

**Issue by Mayanksingla570** [Mayanksingla570/SCM_Final_Evaluation#10]
We aim to enhance the login page of our countdown timer website to improve user experience and security. This issue is a follow-up to our previous login page implementation and focuses on refining its design and functionality.

Tasks:

   1. Conduct a usability review of the current login page to identify pain points and areas for improvement.
   2. Redesign the login page interface to make it more intuitive and visually appealing.
   3. Enhance frontend validation to provide clearer feedback on invalid input.
   4. Test the updated login page across different devices and browsers to ensure consistent performance.

Deadline: 16/05/2024

Thank you for your contributions towards creating a better user experience for our website!

**Comment by mehaks007** [comment]
done with version 2 of login page

**Comment by Mayanksingla570** [comment]
loved your handwork and dedication.
