### ISSUE TITLE
Enhance Contact Page Functionality and Design V2

### ISSUE THREAD

**Issue by Mayanksingla570** [Mayanksingla570/SCM_Final_Evaluation#11]
In continuation of our efforts to improve user engagement and communication on our countdown timer website, we're initiating a second iteration of enhancements for the Contact Us page. This issue focuses on refining the functionality and design of the Contact page to provide users with a seamless and effective communication channel.

Tasks:
   1.  Evaluate the current Contact Us page to identify areas for improvement based on user feedback and usability testing.
   2.  Revise the layout and visual design of the Contact page to make it more visually appealing and user-friendly.
   3.  Introduce additional fields or options in the contact form to gather relevant information from users, such as subject categories or 
        priority levels.
   4. Test the updated Contact page across various devices and browsers to ensure compatibility and consistent performance.

Deadline: 18/05/2024

Thank you for your contributions towards enhancing our website's communication capabilities!

**Comment by manyaarora11** [comment]
i have done my work and made v2 of my contact page.

**Comment by Mayanksingla570** [comment]
Nice work Manya !!
