### ISSUE TITLE
Implement Login Page for Countdown Timer Website

### ISSUE THREAD

**Issue by Mayanksingla570** [Mayanksingla570/SCM_Final_Evaluation#2]
Hello Mehak!

We want to improve our countdown timer website by adding a login page. This will allow users to create accounts, personalize their countdowns, and save preferences. We invite contributions to implement this feature.

Tasks:
Design a user-friendly login page.
Integrate the login page with our website.

Deadline: 12/05/2024

Thank you for your contributions!

**Comment by mehaks007** [comment]
Done, I did the work.

**Comment by Mayanksingla570** [comment]
Well done.
