### ISSUE TITLE
Implement Contact Page for Countdown Timer Website

### ISSUE THREAD

**Issue by Mayanksingla570** [Mayanksingla570/SCM_Final_Evaluation#3]
Hello Manya!

We're aiming to enhance user interaction on our countdown timer website by adding a contact page. This will provide users with a means to reach out to us for support, feedback, or inquiries. We're seeking contributions to implement this feature.

Tasks:
1. Design an intuitive contact page.
2. Ensure the contact form is user-friendly and accessible.
3. Integrate the contact page seamlessly into our website.

Deadline: 15/05/2024

Thank you for your contributions!

**Comment by manyaarora11** [comment]
I have completed my work on time.

**Comment by Mayanksingla570** [comment]
Nice work Manya, Contact us page is looking very professional.
