### ISSUE TITLE
Implement About Us Page for Countdown Timer Website

### ISSUE THREAD

**Issue by Mayanksingla570** [Mayanksingla570/SCM_Final_Evaluation#5]
Hello Mehak!

As part of enhancing our countdown timer website, we're looking to create an "About Us" page to provide users with information about our team and mission. This page will help users understand the purpose behind our website and the people involved in its development. We invite contributions to implement this feature.

Tasks:

   1. Design an appealing "About Us" page layout.
   2. Write engaging content to describe our team and mission.
   3. Ensure the page is responsive and accessible across different devices.
   4. Integrate the "About Us" page with our website navigation.

Deadline: 15/05/2024

Thank you for your contributions!

**Comment by mehaks007** [comment]
i have completed my work, you can evaluate my work.

**Comment by Mayanksingla570** [comment]
Good Work, i liked your dedication for our project.
