### ISSUE TITLE
Implement Sign Up Page for Countdown Timer Website 

### ISSUE THREAD

**Issue by Mayanksingla570** [Mayanksingla570/SCM_Final_Evaluation#6]
Hello Manya!!

In order to enhance the user experience and functionality of our countdown timer website, we're eager to introduce a sign-up page. This feature will enable users to create accounts, personalize their countdowns, and access additional features. We're seeking assistance from the community to implement this essential component.

Tasks:

   1. Design a user-friendly sign-up page interface.
   2. Validate user input to ensure data accuracy and security.
   3. Integrate the sign-up page seamlessly with our website's existing structure.
   
Deadline: 16/05/2024

Thank you for your contributions!

**Comment by manyaarora11** [comment]
I have completed my work

**Comment by Mayanksingla570** [comment]
i Liked your work..
